name: Fly Deploy
on: 
  workflow_dispatch:
  push:
#  schedule:
#    - cron: '0 4 1 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  UUID: ${{ secrets.UUID }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Install flyctl
       run: |
       curl -L https://fly.io/install.sh | sh
      # 将 flyctl 添加到 PATH 环境变量，以便后续步骤可以找到
      export PATH="$PATH:$HOME/.fly/bin"
      echo "PATH=$PATH" >> $GITHUB_ENV # 将 PATH 设置为环境变量，供后续步骤使用

      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          sh ./deploy.sh
